Ft add favicon
atlp-rwanda/atlp-devpulse-fn pull request #124
Opened 2024-09-12 21:55 UTC by Philimuhire

2024-09-14 15:05 UTC, mugishaj092 requested changes
Fix codeclimate and rebase also logo is not visible 
<img width="128" alt="image" src="https://github.com/user-attachments/assets/a7329d63-0bd8-4caa-a97b-897be17a1fa9">

2024-09-14 15:05 UTC, mugishaj092 commented on package.json
> +    "dev": "webpack serve --port 3005",
I believe we don't need to specify the port here, as it has already been set in the webpack.config.js file.

2024-09-14 15:05 UTC, mugishaj092 commented on public/index.html
I also think this file might not be necessary, as we are already using the index.html located in the root directory.

2024-09-15 13:33 UTC, Philimuhire commented on public/index.html
This file was already there before I make changes. Could it be better to remove it?

2024-09-16 11:08 UTC, mugishaj092 requested changes

2024-09-16 11:08 UTC, mugishaj092 commented on package.json
> -    "next-link": "^2.0.0",
We have issue on this package

2024-09-16 18:11 UTC, robsdagreat approved these changes

2024-09-17 05:04 UTC, hbapte approved these changes
well done

2024-09-17 08:24 UTC, Prince-Kid commented
Well Done

2024-09-17 08:26 UTC, Prince-Kid approved these changes
looking good

2024-09-23 03:57 UTC, mugishaj092 requested changes
looks good so far but this build file is not nessary

2024-09-24 11:09 UTC, mugishaj092 approved these changes

2024-09-24 11:21 UTC, mugishaj092 approved these changes

2024-09-25 11:44 UTC, merged