Sidebar Links Review
atlp-rwanda/atlp-devpulse-fn pull request #128
Opened 2024-09-13 11:25 UTC by hbapte

PR  for removing unused and duplicate sider bar links

2024-09-14 19:17 UTC, robsdagreat requested changes
Consider resolving the errors and also pull the latest changes for the code climate failure to be resolved

2024-09-15 10:23 UTC, robsdagreat approved these changes
Well done @hbapte !

2024-09-16 06:27 UTC, MnorbertVii commented
well done @hbapte

2024-09-16 06:33 UTC, MnorbertVii commented
consider informing the one you requested for a review , an approval for the PR to be merged.

2024-09-16 07:26 UTC, niyibi250 approved these changes

2024-09-16 07:29 UTC, Ishimwe7 approved these changes
well done @hbapte

2024-09-16 17:53 UTC, tysepa approved these changes
Make it clear by removing that code  in comment

2024-09-17 05:52 UTC, mugishaj092 approved these changes

2024-09-17 05:54 UTC, mugishaj092 approved these changes

2024-09-17 05:54 UTC, mugishaj092 commented on src/components/sidebar/sidebarItems.tsx
> -    icon: <Icon icon="fluent:people-team-20-filled"></Icon>,
remove those comments and rebase

2024-09-17 05:57 UTC, mugishaj092 requested changes

2024-09-17 05:57 UTC, mugishaj092 commented on src/components/sidebar/sidebarItems.tsx
> -    title: 'Admins',
remove those comments and rebase

2024-09-17 06:10 UTC, hbapte commented on src/components/sidebar/sidebarItems.tsx
> -    icon: <Icon icon="fluent:people-team-20-filled"></Icon>,
solved

2024-09-17 06:12 UTC, hbapte commented
> Make it clear by removing that code in comment

Done

2024-09-20 09:40 UTC, mugishaj092 approved these changes

2024-09-23 08:42 UTC, ncutixavier approved these changes

2024-09-23 08:43 UTC, merged