sidebar responsiveness
atlp-rwanda/atlp-devpulse-fn pull request #17
Opened 2022-10-24 15:16 UTC by GilbertUp

### What does this PR does?
- This PR responsive side-bar and it has Nav bar!
## How can i test this PR?
clone this [repo](https://github.com/atlp-rwanda/atlp-devpulse-fn.git)
-run run command git checkout ft-side-bar-responsiveness
- run npm i and finally npm run start to start the server.

2022-10-25 16:23 UTC, tysepa requested changes
move that conflicts and makes sure your code is obvious in other to remove unused code like the one you put in the comment

2022-10-28 12:42 UTC, tysepa approved these changes
looks good

2022-10-28 13:03 UTC, capitale250 requested changes
squash the commits

2022-10-28 13:03 UTC, capitale250 commented on src/components/profileDropdown.tsx
> +            {/* <p className="font-bold text-sm text-gray-700 dark:text-gray-300">
commented codes

2022-10-28 13:03 UTC, capitale250 commented on src/components/profileDropdown.tsx
> +            {/* <p className="font-bold text-sm text-gray-700 dark:text-gray-300">
commented codes

2022-10-28 13:03 UTC, capitale250 commented on webpack.config.js
> -        sys: require.resolve('util'),
are we loosing all this

2022-10-28 13:03 UTC, capitale250 requested changes
squash the commits

2022-10-28 13:28 UTC, merged