initialized a settings component
atlp-rwanda/atlp-devpulse-fn pull request #171
Opened 2024-09-30 07:10 UTC by Philimuhire

2024-10-06 17:53 UTC, robsdagreat approved these changes

2024-10-07 06:49 UTC, Prince-Kid approved these changes

2024-10-09 15:16 UTC, mugishaj092 requested changes
you made many unnecessary changes and routing to setting page is not working and also you have many commits

2024-10-09 21:08 UTC, closed without merging

2024-10-09 21:09 UTC, Philimuhire commented
Closed this pull request and raised pull request of ft-preferences