Admin Dashboard
atlp-rwanda/atlp-devpulse-fn pull request #181
Opened 2024-10-02 20:14 UTC by Mugisha146

2024-10-03 07:59 UTC, MnorbertVii requested changes
hi @Mugisha146 I noticed that the time displayed in Overall performance statistics section is currently static and does not update in real-time. This could lead to confusion for users as they may think the information is up to date when it’s not. 

also, the number being displayed in all trainees component is not matching the number of trainees we have on Trainees page which I think should match as you did for cycles, etc.

it could be great if you work on showing dynamic data even for All coordinators component if they are there.

2024-10-03 09:10 UTC, Mugisha146 commented
> hi @Mugisha146 I noticed that the time displayed in Overall performance statistics section is currently static and does not update in real-time. This could lead to confusion for users as they may think the information is up to date when it’s not.

Now Solved, Thanks

2024-10-03 10:19 UTC, mugishaj092 requested changes
solve codeclimate issue and remember to add credentials  work on norberts feedback

2024-10-03 10:20 UTC, MnorbertVii commented
solve code climate issues

2024-10-04 10:36 UTC, MnorbertVii approved these changes

2024-10-07 09:14 UTC, mutsinziisaac approved these changes

2024-10-07 21:16 UTC, mugishaj092 approved these changes

2024-10-08 06:51 UTC, Ishimwe7 approved these changes
Well done @Mugisha146

2024-10-08 08:33 UTC, ncutixavier commented
This PR has conflicts

2024-10-08 09:10 UTC, Mugisha146 commented
> This PR has conflicts

Solved

2024-10-08 11:30 UTC, ncutixavier approved these changes

2024-10-08 11:30 UTC, ncutixavier commented
This PR has many commits

2024-10-08 14:02 UTC, Mugisha146 commented
> This PR has many commits

Solved, Now it has 1 commit

2024-10-09 08:23 UTC, ncutixavier reviewed
Please remove all unnecessary logs

2024-10-09 08:23 UTC, ncutixavier commented on src/redux/actions/users.ts
> +    console.error("Error fetching coordinators:", err);
Remove all logs

2024-10-09 09:48 UTC, Mugisha146 commented on src/redux/actions/users.ts
> +    console.error("Error fetching coordinators:", err);
Done

2024-10-09 11:42 UTC, ncutixavier approved these changes

2024-10-09 11:42 UTC, merged