soft deleted trainees listing
atlp-rwanda/atlp-devpulse-fn pull request #21
Opened 2022-10-26 23:28 UTC by gerard1001

**What does this PR do?**  
Listing all soft deleted trainees plus ### pagination.
How should this be manually tested?  
Clone the repo with git clone https://github.com/atlp-rwanda/atlp-devpulse-fn
checkout to branch ft-soft-deleted-trainee-list
Install all packages by running npm install
To start app run npm run dev

2022-10-27 10:33 UTC, BenIraa approved these changes

2022-10-30 09:25 UTC, un-anelka approved these changes

2022-11-01 07:05 UTC, UmuhireJessie requested changes
Nice here! Please make sure that the following are checked

- Rebase and test again your branch [all features should be working, free of errors]
- Use the `NavBar` component created
- Test the responsiveness of your page `/trash` and other pages [they should all work fine]
- Add the filter functionality on this page refer to the one in `/filter_trainee` on 
![image](https://user-images.githubusercontent.com/86103578/199177613-45a69b2e-d8d9-4547-8de7-d09b909b89e8.png)
ping me if you need help

2022-11-10 11:34 UTC, tysepa approved these changes

2022-11-10 11:35 UTC, tysepa commented
But remember to solve this conflict it looking bad with this conflict

2022-11-19 15:05 UTC, closed without merging