Ft filter trainee
atlp-rwanda/atlp-devpulse-fn pull request #22
Opened 2022-10-27 15:47 UTC by UmuhireJessie

### What does this PR do?
- Filters and Searches a trainee by an attribute
### How should this be manually tested?
- Run `git clone https://github.com/atlp-rwanda/atlp-devpulse-fn` to clone the project
- Run `cd atlp-devpulse-fn` to go to the root project
- Run `git fetch` to fetch all branches to your local machine
- Run `git checkout ft-filter-trainee` 
- Run `cp .env.example .env` and setup dotenv variables in `.env` file created
- Run `npm i` or `npm install` to install all used dependencies
- Run `npm run dev` to start the server
### What to expect?
The filtered data will be retrieved every time a character is entered in the search box.

### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/86103578/198336870-916d97a0-fb59-42a6-ac48-db6c86501dda.png)
![image](https://user-images.githubusercontent.com/86103578/198337068-04a23b15-67e0-4fad-b18b-d898104c3ece.png)

### Questions:

2022-10-27 21:37 UTC, tysepa approved these changes

2022-10-27 22:43 UTC, gerard1001 commented
Everything is good, just need to rebase.

2022-10-28 10:16 UTC, gerard1001 requested changes
Make changes on the pagination.

2022-10-28 12:28 UTC, gerard1001 approved these changes

2022-10-28 20:47 UTC, merged