fix(#157): Adding updating profile functionality
atlp-rwanda/atlp-devpulse-fn pull request #228
Opened 2024-10-24 19:55 UTC by Ismaelmurekezi

### PR Description
This PR is for allowing user to update their profile information  ensuring a smooth and secure process for managing personal details. 

### Description of the task that was expected to deliver

1. Allow users to edit personal information, such as name, email, phone number, and profile picture.
2. Ensure input validation for fields like email format, phone number, and required fields.
3. Enable users to upload, update, or remove their profile pictures.
4. Provide options for users to update passwords securely.
5. Allow users to edit personal information, such as name, email, phone number, and profile picture.
6. Include password strength validation ,ensure that all changes are saved dynamically and updated in real time.
7. Add a confirmation message or modal once the profile has been successfully updated.

### How to test this PR
### Locally

- clone this repo and run npm install to install dependencies
- switch to ft-update-profile branch 
- start application by npm run dev
- Create account and login with your credential
- Under profile image on right top corn click it 
- Choose profile
- There you can update any of your information and confirm it by clicking update button

### Deployed 
You follow same steps as those for local 
deployed Link: https://atlp-devpulse-fn-git-ft-upda-10ab6a-devpulses-projects-62c56cf1.vercel.app/

Credentials to use:
Email: admin@example.com
Password: password123  OR

Email: jean@gmail.com
Password: password@123

Issue link: https://github.com/atlp-rwanda/atlp-devpulse-fn/issues/157

###Screenshots
![update profile](https://github.com/user-attachments/assets/f716c252-6654-4362-b75d-9cb413223eb2)

![update profile1](https://github.com/user-attachments/assets/3ee18dda-6e6c-4ebe-be64-c675465fb1e8)

2024-10-24 20:54 UTC, Mugisha146 approved these changes
Good Job

2024-10-24 21:23 UTC, MnorbertVii requested changes
what if you remove that page which contains the button to update profile, after clicking profile in the drop-down menu, and reach on the page straight after clicking profile.? 

Thanks for the feedback, but removing that page which contain button is good option ,because someone can't reach update profile page without passing first to profile page

2024-10-25 00:40 UTC, MnorbertVii commented
> what if you remove that page which contains the button to update profile, after clicking profile in the drop-down menu, and reach on the page straight after clicking profile.?
> 
> Thanks for the feedback, but removing that page which contain button is good option ,because someone can't reach update profile page without passing first to profile page

ok

2024-10-25 05:09 UTC, Philimuhire approved these changes

2024-10-25 07:10 UTC, SaddockAime approved these changes

2024-10-25 08:17 UTC, MnorbertVii approved these changes

2024-10-25 08:27 UTC, ncutixavier approved these changes

2024-10-25 08:27 UTC, merged