Fix Deployment Envs
atlp-rwanda/atlp-devpulse-fn pull request #280
Opened 2024-11-29 20:04 UTC by ndahimana154

2024-12-02 13:20 UTC, ceelogre reviewed
Connect this to the main backend.

2024-12-03 07:11 UTC, ndahimana154 commented
> Connect this to the main backend.

Completed.

2024-12-03 12:49 UTC, ceelogre requested changes

2024-12-03 12:49 UTC, ceelogre commented on .github/workflows/docker-img.yml
> +            docker ps | grep "$container_id" || exit 1
No need to check the status of the container since you already got the ID and the if block did not run.

2024-12-03 13:38 UTC, ceelogre approved these changes

2024-12-03 13:39 UTC, merged