Ft import and save many trainees from googlesheet v5
atlp-rwanda/atlp-devpulse-fn pull request #35
Opened 2022-11-10 23:39 UTC by Niyonkuru1

## What does this PR do?

Import many trainees and their attributes from google sheet and save them into the mongo database

## Description of Task to be completed?

The admin should copy the URL of his / her google sheet and paste them into the input field of the app, then after hitting load, those data should be copied into the database. If the column of the google sheet is not matching the properties in the database collection, he/she should see the error screen with the steps of how to do it correctly. while if it save correctly, he / she will see the screen saying that uploading is successful.

## How should this be manually tested?

- `Clone the repo`

- `checkout` to branch `ft-import-and-save-many-trainees-from-googlesheet`

- Pull the changes by `git pull`

- Install all packages by running `npm install`

- Start app by `running npm run dev`

## Any background context you want to provide?

Note note **you should use only the configured google sheet url, not every google sheet url will work.**

## What are the relevant pivotal tracker stories?

[Trello Board reference](https://trello.com/c/17S8aqBu/58-import-trainees-google-sheet)

2022-11-16 07:28 UTC, capitale250 commented on src/redux/app/hook.ts
> +import { TypedUseSelectorHook, useDispatch, useSelector } from "react-redux";
we was having this hook src/hooks/hooks.ts

2022-11-17 11:53 UTC, UmuhireJessie requested changes
So far so good! 

1. You might have deleted this toast that shows that importing trainees is being processed, please add it again. Otherwise, a user can not know what's happening 
![image](https://user-images.githubusercontent.com/86103578/202437815-621992e1-06ef-484b-8839-0a19a2c2069f.png)

2. Please consider the suggested changes on the backend too

3. Find a way to save trainee applicants if all checks of trainee attributes are finished. Otherwise `/trainee` will have more trainees compared to `/filter_trainee` page which is a problem.

2022-11-17 11:53 UTC, UmuhireJessie commented on src/redux/actions/PerformLoadDataAction.ts
> +      url: "http://localhost:4000/",
Change `url: "http://localhost:4000/",` to `url: process.env.BACKEND_URL,`

2022-11-17 11:53 UTC, UmuhireJessie commented on src/redux/actions/PerformLoadDataAction.ts
> +      toast.error(`OOPS!!! import failed please match columns 🤯`)
I think you might consider removing the emoji

2022-11-17 11:53 UTC, UmuhireJessie commented on src/redux/actions/PerformLoadDataAction.ts
> +        toast.error(`Not saved please match cohort name !! 🤯`)
same here

2022-11-17 11:53 UTC, UmuhireJessie commented on src/pages/importAndSaveManyTraineesFromGoogleSheet/importAndSaveManyTraineesFromGoogleSheet.tsx
> +                Please enter the correct cycle name which is in Database
Change the message to something simple as @denislohan suggested.
Ex:  `Please enter correct cycle name!`

2022-11-17 16:32 UTC, merged