ft-register-user
atlp-rwanda/atlp-devpulse-fn pull request #67
Opened 2023-08-25 14:43 UTC by nkurunziza1

2023-09-04 17:39 UTC, buka1calvin approved these changes

2023-09-05 14:58 UTC, mjeanbosco19 requested changes
Fix this Error:
Compiled with problems:
×
ERROR in ./node_modules/@fortawesome/react-fontawesome/index.es.js 1:0-64
Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/Users/andelarwanda/Desktop/atlp-devpulse-fn/node_modules/@fortawesome/react-fontawesome'
<img width="1440" alt="Screenshot 2023-09-05 at 16 55 45" src="https://github.com/atlp-rwanda/atlp-devpulse-fn/assets/102979159/d43b135c-bfb1-4825-b24f-8f641e09e590">

2023-09-08 08:47 UTC, dean-daryl approved these changes

2023-09-08 13:26 UTC, Anguandia approved these changes

2023-09-08 13:28 UTC, Anguandia commented
Please address or resolve @mjeanbosco19 's change request. also fix the failing checks, @nkurunziza1

2023-09-08 13:55 UTC, mjeanbosco19 approved these changes

2023-09-08 15:44 UTC, merged