added axios interceptors
atlp-rwanda/atlp-devpulse-fn pull request #7
Opened 2022-10-07 14:04 UTC by Benafrica

#### What does this PR do?
 axios interceptor to catch 401 responses.

#### How should this be manually tested?

Clone this [repo](https://github.com/atlp-rwanda/atlp-devpulse-fn/circleci-project-setup)
run the command git checkout ft-axios-interceptors
run  npm install
run  npm run dev to start the server

2022-10-08 20:27 UTC, tysepa approved these changes
solve that conflict it will be bether

2022-10-10 16:30 UTC, arthurjunior250 requested changes
fix the Circle-ci issues and resolve conflicts

2022-10-11 09:42 UTC, arthurjunior250 approved these changes

2022-10-11 09:43 UTC, denislohan requested changes

2022-10-11 09:43 UTC, denislohan commented on src/utils/axios.tsx
> +        window.location.href = '/';
can we instead redirect to /login

2022-10-11 10:33 UTC, denislohan approved these changes

2022-10-11 10:34 UTC, merged