ft create program
atlp-rwanda/atlp-devpulse-fn pull request #73
Opened 2023-09-12 20:01 UTC by masterchief-00

## What does this PR do?

- adds page to create a program

### Description of Task to be completed?
- N/A

### How should this be manually tested?
- N/A

### Any background context you want to provide?
- N/A

What are the relevant pivotal tracker stories?
N/A

### Screenshots (if appropriate)

<img width="841" alt="Screenshot 2023-09-12 220039" src="https://github.com/atlp-rwanda/atlp-devpulse-fn/assets/87192950/a5d71154-5072-42eb-9617-659e27d818e2">
<img width="790" alt="Screenshot 2023-09-12 194839" src="https://github.com/atlp-rwanda/atlp-devpulse-fn/assets/87192950/199ca8e5-97a7-499d-81bf-08e4daf27e39">

### Questions:
- N/A

2023-09-22 07:28 UTC, mjeanbosco19 commented
Hello @masterchief-00 Is this PR ready for review? If is Ready, please Update the Status?

2023-09-22 13:17 UTC, dean-daryl approved these changes

2023-09-25 11:16 UTC, mjeanbosco19 approved these changes

2023-09-25 13:09 UTC, Anguandia requested changes
Please work with @dean-daryl and @JosephNgabo to resolve or remove the issue of the old vercel deployment

2023-09-25 13:31 UTC, Anguandia approved these changes

2023-09-25 13:32 UTC, merged