Delete program
atlp-rwanda/atlp-devpulse-fn pull request #84
Opened 2023-10-16 21:44 UTC by masterchief-00

## What does this PR do?

- adds the page to delete programs

### Description of Task to be completed?
- N/A

### How should this be manually tested?
- N/A

### Any background context you want to provide?
- N/A

What are the relevant pivotal tracker stories?
N/A

### Screenshots (if appropriate)

### Questions:
- N/A

2023-10-17 12:56 UTC, katros1 approved these changes

2023-10-17 13:05 UTC, mjeanbosco19 approved these changes

2023-10-18 08:15 UTC, Anguandia commented
@masterchief-00 , please rebase to resolve conflicts and if possible, please squash to 1 commit

2023-10-19 06:42 UTC, Anguandia requested changes
Good work @masterchief-00, please squash your commits to max 2 if possible

2023-10-19 08:47 UTC, Anguandia approved these changes

2023-10-19 12:51 UTC, merged