admin update status of candidate application
atlp-rwanda/atlp-devpulse-fn pull request #98
Opened 2023-11-03 12:39 UTC by nkurunziza1

2023-11-14 06:44 UTC, buka1calvin approved these changes

2023-11-14 16:46 UTC, katros1 requested changes
Great job @nkurunziza1, but there small changes you need to make to make page look great:
 Remove the description fields from the list to avoid making the page look messy, especially for long descriptions. 
same applies to the requirements field for the programs

2023-11-20 08:43 UTC, mjeanbosco19 approved these changes

2023-11-20 17:32 UTC, katros1 approved these changes

2023-11-22 14:46 UTC, merged